#!/usr/bin/env python3
"""Read brevis train-lowlevel JSON report, decode promoted macros, emit
src/discovered_macros.zig.

Each macro becomes a const struct entry with a flat array of nodes (indexed
tree representation), so the runtime can walk it without recursion.

Usage:
    python tools/emit_macros.py train_report.json src/discovered_macros.zig
"""
from __future__ import annotations

import json
import sys

# Op name mapping (must mirror lowlevel.OpKind in src/lowlevel.zig)
OP_NAMES = {
    0: "xor_const", 1: "add_const_mod", 2: "rotate_bits", 3: "bit_swap_pair",
    4: "bit_reverse", 5: "negate_mod", 6: "mul_const_odd_mod", 7: "xor_with_shift",
    8: "gray_code", 9: "inv_gray_code",
    10: "xor_prev", 11: "prefix_xor", 12: "diff_mod", 13: "cumsum_mod",
    14: "split_field",
    16: "huffman", 17: "rans", 18: "raw",
}
TERMINALS = {16, 17, 18}


def decode(blob: bytes, pos: int = 0):
    """Decode one canonical-format node starting at `pos`. Returns (tree_dict, new_pos).
    Returns (None, pos+1) for a wildcard (depth-limit truncation marker)."""
    tag = blob[pos]
    pos += 1
    if tag == 0xFF:
        return None, pos
    if tag == 0x00:
        op_kind = blob[pos]
        pos += 1
        return {"kind": "terminal", "op_kind": op_kind}, pos
    if tag == 0x01:
        op_kind = blob[pos]
        pos += 1
        params = int.from_bytes(blob[pos : pos + 4], "little")
        pos += 4
        nxt, pos = decode(blob, pos)
        return {"kind": "chain", "op_kind": op_kind, "params": params, "next": nxt}, pos
    if tag == 0x02:
        op_kind = blob[pos]
        pos += 1
        params = int.from_bytes(blob[pos : pos + 4], "little")
        pos += 4
        hi, pos = decode(blob, pos)
        lo, pos = decode(blob, pos)
        return {"kind": "split", "op_kind": op_kind, "params": params, "hi": hi, "lo": lo}, pos
    raise ValueError(f"unknown tag 0x{tag:02x} at pos {pos-1}")


def has_wildcard(node) -> bool:
    if node is None:
        return True
    if node["kind"] == "terminal":
        return False
    if node["kind"] == "chain":
        return has_wildcard(node["next"])
    if node["kind"] == "split":
        return has_wildcard(node["hi"]) or has_wildcard(node["lo"])
    return True


def flatten(node, out_list) -> int:
    """Append flattened nodes to `out_list`; return root index."""
    idx = len(out_list)
    out_list.append(None)  # placeholder, fill in after recursing
    if node["kind"] == "terminal":
        out_list[idx] = {
            "op_kind": node["op_kind"],
            "params": 0,
            "child_hi": -1,
            "child_lo": -1,
            "is_terminal": True,
        }
    elif node["kind"] == "chain":
        next_idx = flatten(node["next"], out_list)
        out_list[idx] = {
            "op_kind": node["op_kind"],
            "params": node["params"],
            "child_hi": next_idx,
            "child_lo": -1,
            "is_terminal": False,
        }
    elif node["kind"] == "split":
        hi_idx = flatten(node["hi"], out_list)
        lo_idx = flatten(node["lo"], out_list)
        out_list[idx] = {
            "op_kind": node["op_kind"],
            "params": node["params"],
            "child_hi": hi_idx,
            "child_lo": lo_idx,
            "is_terminal": False,
        }
    return idx


def gen_name(node) -> str:
    parts: list[str] = []

    def walk(n):
        if n is None:
            parts.append("any")
        elif n["kind"] == "terminal":
            parts.append(OP_NAMES[n["op_kind"]])
        elif n["kind"] == "chain":
            parts.append(f"{OP_NAMES[n['op_kind']]}_{n['params']:x}")
            walk(n["next"])
        elif n["kind"] == "split":
            parts.append(f"{OP_NAMES[n['op_kind']]}_{n['params']:x}")
            walk(n["hi"])
            walk(n["lo"])

    walk(node)
    return "macro_" + "_".join(parts)


HEADER = """// AUTO-GENERATED by tools/emit_macros.py — do not edit by hand.
// Source: {src}
//
// Each macro is a (name, body) pair where the body is a flat array of
// MacroNodes representing a small tree in indexed-pointer form.

const lowlevel = @import("lowlevel.zig");

pub const MacroNode = struct {{
    op_kind: lowlevel.OpKind,
    params_raw: u32,
    child_hi: i32, // -1 if none
    child_lo: i32, // -1 if none
    is_terminal: bool,
}};

pub const Macro = struct {{
    name: []const u8,
    nodes: []const MacroNode,
    mdl_benefit: i64,
    /// Initial input bits-per-elem this macro is calibrated for (0 = any).
    input_bpe: u8,
}};

"""


def main(in_path: str, out_path: str) -> int:
    with open(in_path) as f:
        report = json.load(f)
    macros = report.get("promoted_macros", {}).get("items", [])

    emitted = []
    skipped = 0
    for m in macros:
        try:
            canonical = bytes.fromhex(m["canonical"])
            tree, _ = decode(canonical)
        except Exception as e:
            print(f"  skip: decode failed ({e})", file=sys.stderr)
            skipped += 1
            continue
        if tree is None or has_wildcard(tree):
            skipped += 1
            continue
        flat: list[dict] = []
        flatten(tree, flat)
        emitted.append({
            "name": gen_name(tree),
            "flat": flat,
            "benefit": m["mdl_benefit"],
            "size": m["size"],
            "count": m["count"],
        })

    lines: list[str] = [HEADER.format(src=in_path)]
    if not emitted:
        lines.append("pub const DISCOVERED: []const Macro = &.{};\n")
    else:
        lines.append("pub const DISCOVERED: []const Macro = &.{\n")
        for m in emitted:
            lines.append("    .{\n")
            lines.append(f'        .name = "{m["name"]}",\n')
            lines.append(f"        .mdl_benefit = {m['benefit']},\n")
            lines.append(f"        .input_bpe = 0,\n")  # MVP: any
            lines.append("        .nodes = &.{\n")
            for n in m["flat"]:
                tt = "true" if n["is_terminal"] else "false"
                lines.append(
                    f"            .{{ .op_kind = .{OP_NAMES[n['op_kind']]}, "
                    f".params_raw = 0x{n['params']:x}, "
                    f".child_hi = {n['child_hi']}, "
                    f".child_lo = {n['child_lo']}, "
                    f".is_terminal = {tt} }},\n"
                )
            lines.append("        },\n")
            lines.append("    },\n")
        lines.append("};\n")

    with open(out_path, "w") as f:
        f.write("".join(lines))
    print(f"emitted {len(emitted)} macros (skipped {skipped} with wildcards) → {out_path}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
