#!/usr/bin/env python3
"""Train a count-based PHOG with Laplace smoothing from JSONL examples
emitted by `brevis collect-training`. Writes a static Zig lookup table to
src/phog.zig.

Usage:
    python tools/train_phog.py training.jsonl src/phog.zig
"""
from __future__ import annotations

import json
import math
import sys
from collections import defaultdict
from pathlib import Path

# Production sets must mirror src/search.zig
T_PROG_PRODUCTIONS = ["tensor_raw", "split_float", "tensor_xor"]
S_PROG_PRODUCTIONS = [
    "raw", "huffman", "rans",
    "delta_raw", "delta_huffman", "delta_rans",
    "bp_raw", "bp_huffman", "bp_rans",
]

POSITIONS = ["root", "split.sign", "split.exp", "split.mant"]
DTYPES = ["F16", "BF16"]                  # only these are supported by brevis
N_LOG2_BUCKETS = 8                        # log2_numel // 4, clamped to [0, 7]
N_NDIM_BUCKETS = 3                        # 1, 2, 3+

# Laplace pseudo-count (per production). Larger = smoother, weaker prior.
LAPLACE_ALPHA = 1.0

# log2(0) is -inf; clamp probabilities to a floor before logging.
PROB_FLOOR = 1e-9


def bucket_log2(log2_numel: int) -> int:
    return max(0, min(N_LOG2_BUCKETS - 1, log2_numel // 4))


def bucket_ndim(ndim: int) -> int:
    return max(0, min(N_NDIM_BUCKETS - 1, ndim - 1))


def bucket_dtype(name: str) -> int:
    try:
        return DTYPES.index(name)
    except ValueError:
        return -1   # unsupported; skip


def main(in_path: str, out_path: str) -> int:
    counts: dict[tuple, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    n_examples = 0
    with open(in_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            ex = json.loads(line)
            di = bucket_dtype(ex["dtype"])
            if di < 0:
                continue
            li = bucket_log2(int(ex["log2_numel"]))
            ni = bucket_ndim(int(ex["ndim"]))
            ctx = (ex["pos"], di, li, ni)
            counts[ctx][ex["prod"]] += 1
            n_examples += 1

    # Build smoothed distributions.
    smoothed: dict[tuple, list[float]] = {}
    for ctx, c in counts.items():
        productions = T_PROG_PRODUCTIONS if ctx[0] == "root" else S_PROG_PRODUCTIONS
        n_p = len(productions)
        total = sum(c.values()) + LAPLACE_ALPHA * n_p
        smoothed[ctx] = [
            (c.get(p, 0) + LAPLACE_ALPHA) / total for p in productions
        ]

    # Tabulate every (pos, dtype, log2, ndim) into the output. For unseen
    # contexts, fall back to a uniform Laplace distribution — no observation
    # means we have no opinion.
    def uniform(n: int) -> list[float]:
        return [1.0 / n] * n

    out_lines: list[str] = []
    out_lines.append("// AUTO-GENERATED by tools/train_phog.py — do not edit by hand.\n")
    out_lines.append(f"// Source: {in_path}\n")
    out_lines.append(f"// {n_examples} training examples → {len(counts)} populated contexts\n\n")
    out_lines.append('const search = @import("search.zig");\n')
    out_lines.append('const types = @import("types.zig");\n\n')
    out_lines.append(f"pub const N_LOG2_BUCKETS: usize = {N_LOG2_BUCKETS};\n")
    out_lines.append(f"pub const N_NDIM_BUCKETS: usize = {N_NDIM_BUCKETS};\n")
    out_lines.append(f"pub const N_DTYPES: usize = {len(DTYPES)};\n\n")

    out_lines.append("pub const Position = enum(u8) { root, split_sign, split_exp, split_mant };\n\n")

    # Root table: predicts T_PROG production.
    out_lines.append(
        "// log_probs[i] = -log2(P(production_i | ctx)) * 1024 (fixed-point u32).\n"
        "// 0xFFFFFFFF means impossible; lower = more likely.\n\n"
    )
    out_lines.append("pub const RootEntry = struct { log_probs_neg: [3]u32 };\n")
    out_lines.append("pub const StreamEntry = struct { log_probs_neg: [9]u32 };\n\n")

    def fmt_row(probs: list[float]) -> str:
        items = []
        for p in probs:
            if p < PROB_FLOOR:
                items.append("0xFFFFFFFF")
            else:
                # -log2(p) is positive; scale by 1024 and round to u32.
                v = round(-math.log2(p) * 1024)
                v = max(0, min(0xFFFFFFFF, v))
                items.append(f"{v}")
        return "{ " + ", ".join(items) + " }"

    # Root table dimensions: [dtype][log2_bucket][ndim_bucket]
    out_lines.append(
        f"pub const ROOT: [{len(DTYPES)}][{N_LOG2_BUCKETS}][{N_NDIM_BUCKETS}]RootEntry = .{{\n"
    )
    for di in range(len(DTYPES)):
        out_lines.append(f"    // dtype={DTYPES[di]}\n    .{{\n")
        for li in range(N_LOG2_BUCKETS):
            out_lines.append(f"        // log2_bucket={li} (log2_numel ∈ [{li * 4},{li * 4 + 4}))\n        .{{\n")
            for ni in range(N_NDIM_BUCKETS):
                ctx = ("root", di, li, ni)
                probs = smoothed.get(ctx, uniform(len(T_PROG_PRODUCTIONS)))
                out_lines.append(f"            .{{ .log_probs_neg = .{fmt_row(probs)} }},  // ndim={ni + 1}\n")
            out_lines.append("        },\n")
        out_lines.append("    },\n")
    out_lines.append("};\n\n")

    # Stream table dimensions: [pos][dtype][log2_bucket][ndim_bucket]
    out_lines.append(
        f"pub const STREAM: [3][{len(DTYPES)}][{N_LOG2_BUCKETS}][{N_NDIM_BUCKETS}]StreamEntry = .{{\n"
    )
    for pi, pos_name in enumerate(["split.sign", "split.exp", "split.mant"]):
        out_lines.append(f"    // pos={pos_name}\n    .{{\n")
        for di in range(len(DTYPES)):
            out_lines.append(f"        // dtype={DTYPES[di]}\n        .{{\n")
            for li in range(N_LOG2_BUCKETS):
                out_lines.append(f"            // log2_bucket={li}\n            .{{\n")
                for ni in range(N_NDIM_BUCKETS):
                    ctx = (pos_name, di, li, ni)
                    probs = smoothed.get(ctx, uniform(len(S_PROG_PRODUCTIONS)))
                    out_lines.append(f"                .{{ .log_probs_neg = .{fmt_row(probs)} }},  // ndim={ni + 1}\n")
                out_lines.append("            },\n")
            out_lines.append("        },\n")
        out_lines.append("    },\n")
    out_lines.append("};\n\n")

    # Helper functions.
    out_lines.append("""
pub fn dtypeIdx(d: types.Dtype) ?u8 {
    return switch (d) {
        .f16 => 0,
        .bf16 => 1,
        else => null,
    };
}

pub fn log2Bucket(log2_numel: u8) u8 {
    const b = log2_numel / 4;
    return if (b >= N_LOG2_BUCKETS) @intCast(N_LOG2_BUCKETS - 1) else b;
}

pub fn ndimBucket(ndim: usize) u8 {
    if (ndim <= 1) return 0;
    if (ndim == 2) return 1;
    return 2;
}

fn argminU32(arr: []const u32) u8 {
    var best: u8 = 0;
    var best_v: u32 = arr[0];
    for (arr[1..], 1..) |v, i| if (v < best_v) {
        best_v = v;
        best = @intCast(i);
    };
    return best;
}

/// True iff PHOG has no useful opinion for this context (all production
/// probabilities are within rounding of each other). Untrained contexts get
/// uniform Laplace which we read as "fall back to A* search".
fn isUninformative(arr: []const u32) bool {
    const first = arr[0];
    for (arr[1..]) |v| if (v != first) return false;
    return true;
}

pub fn predictRoot(dtype: types.Dtype, log2_numel: u8, ndim: usize) ?search.TProgProduction {
    const di = dtypeIdx(dtype) orelse return null;
    const li = log2Bucket(log2_numel);
    const ni = ndimBucket(ndim);
    const e = ROOT[di][li][ni];
    if (isUninformative(&e.log_probs_neg)) return null;
    return @enumFromInt(argminU32(&e.log_probs_neg));
}

pub fn predictStream(slot: u8, dtype: types.Dtype, log2_numel: u8, ndim: usize) ?search.StreamProduction {
    const di = dtypeIdx(dtype) orelse return null;
    const li = log2Bucket(log2_numel);
    const ni = ndimBucket(ndim);
    const e = STREAM[slot][di][li][ni];
    if (isUninformative(&e.log_probs_neg)) return null;
    return @enumFromInt(argminU32(&e.log_probs_neg));
}
""")

    Path(out_path).write_text("".join(out_lines))
    print(f"wrote {out_path}: {len(counts)} populated contexts, {n_examples} examples")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
