// AUTO-GENERATED by tools/emit_macros.py — do not edit by hand.
// Source: /tmp/lowlevel_train_full.json
//
// Each macro is a (name, body) pair where the body is a flat array of
// MacroNodes representing a small tree in indexed-pointer form.

const lowlevel = @import("lowlevel.zig");

pub const MacroNode = struct {
    op_kind: lowlevel.OpKind,
    params_raw: u32,
    child_hi: i32, // -1 if none
    child_lo: i32, // -1 if none
    is_terminal: bool,
};

pub const Macro = struct {
    name: []const u8,
    nodes: []const MacroNode,
    mdl_benefit: i64,
    /// Initial input bits-per-elem this macro is calibrated for (0 = any).
    input_bpe: u8,
};

pub const DISCOVERED: []const Macro = &.{
    .{
        .name = "macro_xor_with_shift_2_split_field_80200_rans_rans",
        .mdl_benefit = 370,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .xor_with_shift, .params_raw = 0x2, .child_hi = 1, .child_lo = -1, .is_terminal = false },
            .{ .op_kind = .split_field, .params_raw = 0x80200, .child_hi = 2, .child_lo = 3, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
    .{
        .name = "macro_split_field_80200_rans_rans",
        .mdl_benefit = 273,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .split_field, .params_raw = 0x80200, .child_hi = 1, .child_lo = 2, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
    .{
        .name = "macro_split_field_80107_rans_rans",
        .mdl_benefit = 33,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .split_field, .params_raw = 0x80107, .child_hi = 1, .child_lo = 2, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
    .{
        .name = "macro_split_field_80206_rans_rans",
        .mdl_benefit = 19,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .split_field, .params_raw = 0x80206, .child_hi = 1, .child_lo = 2, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
    .{
        .name = "macro_split_field_80404_rans_xor_prev_0_rans",
        .mdl_benefit = 19,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .split_field, .params_raw = 0x80404, .child_hi = 1, .child_lo = 2, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
            .{ .op_kind = .xor_prev, .params_raw = 0x0, .child_hi = 3, .child_lo = -1, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
    .{
        .name = "macro_split_field_80404_rans_rans",
        .mdl_benefit = 17,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .split_field, .params_raw = 0x80404, .child_hi = 1, .child_lo = 2, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
    .{
        .name = "macro_xor_prev_0_rans",
        .mdl_benefit = 15,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .xor_prev, .params_raw = 0x0, .child_hi = 1, .child_lo = -1, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
    .{
        .name = "macro_split_field_80107_rans_xor_prev_0_rans",
        .mdl_benefit = 4,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .split_field, .params_raw = 0x80107, .child_hi = 1, .child_lo = 2, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
            .{ .op_kind = .xor_prev, .params_raw = 0x0, .child_hi = 3, .child_lo = -1, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
    .{
        .name = "macro_negate_mod_0_split_field_80107_rans_rans",
        .mdl_benefit = 1,
        .input_bpe = 0,
        .nodes = &.{
            .{ .op_kind = .negate_mod, .params_raw = 0x0, .child_hi = 1, .child_lo = -1, .is_terminal = false },
            .{ .op_kind = .split_field, .params_raw = 0x80107, .child_hi = 2, .child_lo = 3, .is_terminal = false },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
            .{ .op_kind = .rans, .params_raw = 0x0, .child_hi = -1, .child_lo = -1, .is_terminal = true },
        },
    },
};
