// AUTO-GENERATED by tools/train_phog.py — do not edit by hand.
// Source: /tmp/training.jsonl
// 804 training examples → 16 populated contexts

const search = @import("search.zig");
const types = @import("types.zig");

pub const N_LOG2_BUCKETS: usize = 8;
pub const N_NDIM_BUCKETS: usize = 3;
pub const N_DTYPES: usize = 2;

pub const Position = enum(u8) { root, split_sign, split_exp, split_mant };

// log_probs[i] = -log2(P(production_i | ctx)) * 1024 (fixed-point u32).
// 0xFFFFFFFF means impossible; lower = more likely.

pub const RootEntry = struct { log_probs_neg: [3]u32 };
pub const StreamEntry = struct { log_probs_neg: [9]u32 };

pub const ROOT: [2][8][3]RootEntry = .{
    // dtype=F16
    .{
        // log2_bucket=0 (log2_numel ∈ [0,4))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=1 (log2_numel ∈ [4,8))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=2 (log2_numel ∈ [8,12))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=3 (log2_numel ∈ [12,16))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=4 (log2_numel ∈ [16,20))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=5 (log2_numel ∈ [20,24))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=6 (log2_numel ∈ [24,28))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=7 (log2_numel ∈ [28,32))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
    },
    // dtype=BF16
    .{
        // log2_bucket=0 (log2_numel ∈ [0,4))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=1 (log2_numel ∈ [4,8))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=2 (log2_numel ∈ [8,12))
        .{
            .{ .log_probs_neg = .{ 5719, 63, 5719 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=3 (log2_numel ∈ [12,16))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=4 (log2_numel ∈ [16,20))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 5688, 64, 5688 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=5 (log2_numel ∈ [20,24))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 6984, 26, 6984 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=6 (log2_numel ∈ [24,28))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 2378, 755, 2378 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
        // log2_bucket=7 (log2_numel ∈ [28,32))
        .{
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=1
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=2
            .{ .log_probs_neg = .{ 1623, 1623, 1623 } },  // ndim=3
        },
    },
};

pub const STREAM: [3][2][8][3]StreamEntry = .{
    // pos=split.sign
    .{
        // dtype=F16
        .{
            // log2_bucket=0
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=1
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=2
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=3
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=4
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=5
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=6
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=7
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
        },
        // dtype=BF16
        .{
            // log2_bucket=0
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=1
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=2
            .{
                .{ .log_probs_neg = .{ 5893, 4869, 269, 5893, 5893, 5893, 5893, 5893, 5893 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=3
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=4
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 5865, 242, 5865, 5865, 5865, 5865, 5865, 5865, 5865 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=5
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 7060, 157, 4683, 7060, 7060, 7060, 7060, 7060, 7060 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=6
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3542, 2518, 2518, 3542, 3542, 3542, 3542, 3542, 3542 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=7
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
        },
    },
    // pos=split.exp
    .{
        // dtype=F16
        .{
            // log2_bucket=0
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=1
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=2
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=3
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=4
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=5
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=6
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=7
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
        },
        // dtype=BF16
        .{
            // log2_bucket=0
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=1
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=2
            .{
                .{ .log_probs_neg = .{ 5893, 4270, 303, 5893, 5893, 5893, 5893, 5893, 5893 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=3
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=4
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 5865, 5865, 242, 5865, 5865, 5865, 5865, 5865, 5865 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=5
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 7060, 7060, 103, 7060, 7060, 7060, 7060, 7060, 7060 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=6
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3542, 3542, 1919, 3542, 3542, 3542, 3542, 3542, 3542 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=7
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
        },
    },
    // pos=split.mant
    .{
        // dtype=F16
        .{
            // log2_bucket=0
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=1
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=2
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=3
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=4
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=5
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=6
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=7
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
        },
        // dtype=BF16
        .{
            // log2_bucket=0
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=1
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=2
            .{
                .{ .log_probs_neg = .{ 5893, 2821, 5893, 5893, 5893, 5893, 5893, 2351, 918 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=3
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=4
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 5865, 5865, 242, 5865, 5865, 5865, 5865, 5865, 5865 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=5
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 7060, 7060, 103, 7060, 7060, 7060, 7060, 7060, 7060 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=6
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3542, 3542, 1919, 3542, 3542, 3542, 3542, 3542, 3542 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
            // log2_bucket=7
            .{
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=1
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=2
                .{ .log_probs_neg = .{ 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246, 3246 } },  // ndim=3
            },
        },
    },
};


pub fn dtypeIdx(d: types.Dtype) ?u8 {
    return switch (d) {
        .f16 => 0,
        .bf16 => 1,
        else => null,
    };
}

pub fn log2Bucket(log2_numel: u8) u8 {
    const b = log2_numel / 4;
    return if (b >= N_LOG2_BUCKETS) @intCast(N_LOG2_BUCKETS - 1) else b;
}

pub fn ndimBucket(ndim: usize) u8 {
    if (ndim <= 1) return 0;
    if (ndim == 2) return 1;
    return 2;
}

fn argminU32(arr: []const u32) u8 {
    var best: u8 = 0;
    var best_v: u32 = arr[0];
    for (arr[1..], 1..) |v, i| if (v < best_v) {
        best_v = v;
        best = @intCast(i);
    };
    return best;
}

/// True iff PHOG has no useful opinion for this context (all production
/// probabilities are within rounding of each other). Untrained contexts get
/// uniform Laplace which we read as "fall back to A* search".
fn isUninformative(arr: []const u32) bool {
    const first = arr[0];
    for (arr[1..]) |v| if (v != first) return false;
    return true;
}

pub fn predictRoot(dtype: types.Dtype, log2_numel: u8, ndim: usize) ?search.TProgProduction {
    const di = dtypeIdx(dtype) orelse return null;
    const li = log2Bucket(log2_numel);
    const ni = ndimBucket(ndim);
    const e = ROOT[di][li][ni];
    if (isUninformative(&e.log_probs_neg)) return null;
    return @enumFromInt(argminU32(&e.log_probs_neg));
}

pub fn predictStream(slot: u8, dtype: types.Dtype, log2_numel: u8, ndim: usize) ?search.StreamProduction {
    const di = dtypeIdx(dtype) orelse return null;
    const li = log2Bucket(log2_numel);
    const ni = ndimBucket(ndim);
    const e = STREAM[slot][di][li][ni];
    if (isUninformative(&e.log_probs_neg)) return null;
    return @enumFromInt(argminU32(&e.log_probs_neg));
}
